sensor:
##    ## ##      ## ##     ##     ######  ######## ##    ##  ######   #######  ########  
##   ##  ##  ##  ## ##     ##    ##    ## ##       ###   ## ##    ## ##     ## ##     ## 
##  ##   ##  ##  ## ##     ##    ##       ##       ####  ## ##       ##     ## ##     ## 
#####    ##  ##  ## #########     ######  ######   ## ## ##  ######  ##     ## ########  
##  ##   ##  ##  ## ##     ##          ## ##       ##  ####       ## ##     ## ##   ##   
##   ##  ##  ##  ## ##     ##    ##    ## ##       ##   ### ##    ## ##     ## ##    ##  
##    ##  ###  ###  ##     ##     ######  ######## ##    ##  ######   #######  ##     ## 

## KWH 
  - platform: template
    sensors:
      kwh_consumption_total:
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_total') }}

  - platform: template
    sensors:
      kwh_consumption_today:
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_today') }}    

  - platform: template
    sensors:
      kwh_consumption_startofday:
        unique_id: kwh_consumption_startofday
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_startofday') }}    

  - platform: template
    sensors:
      kwh_consumption_startofmonth:
        unique_id: kwh_consumption_startofmonth
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_startofmonth') }}    

  - platform: template
    sensors:
      kwh_consumption_startofyear:
        unique_id: kwh_consumption_startofyear
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_startofyear') }}    

  - platform: template
    sensors:
      kwh_consumption_lastday:
        unique_id: kwh_consumption_lastday
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_lastday') }}    

  - platform: template
    sensors:
      kwh_consumption_thismonth:
        unique_id: kwh_consumption_thismonth
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_thismonth') }}

  - platform: template
    sensors:
      kwh_consumption_lastmonth:
        unique_id: kwh_consumption_lastmonth
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_lastmonth') }}

  - platform: template
    sensors:
      kwh_consumption_thisyear:
        unique_id: kwh_consumption_thisyear
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_consumption_thisyear') }}

  - platform: template
    sensors:
      kwh_active_usage:
        unique_id: kwh_active_usage
        device_class: energy
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_active_usage') }}
      
  - platform: template
    sensors:
      kwh_min:
        unique_id: kwh_min
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_min') }}
      
  - platform: template
    sensors:
      kwh_max:
        unique_id: kwh_max
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.kwh_max') }}

  - platform: template
    sensors:
      monthly_kwh_peak_hour:
        unique_id: monthly_kwh_peak_hour
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.monthly_kwh_peak_hour') }}

  - platform: template
    sensors:
      monthly_power_peak_prize:
        unique_id: monthly_power_peak_prize
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.monthly_power_peak_prize') }}

  - platform: template
    sensors:
      price_usage_now:
        unique_id: price_usage_now
        icon_template: mdi:fire
        unit_of_measurement: "kWh"
        value_template: >
          {{ states('input_number.price_usage_now') }}




########  ########  ####  ######  ########     ######  ######## ##    ##  ######   #######  ########  
##     ## ##     ##  ##  ##    ## ##          ##    ## ##       ###   ## ##    ## ##     ## ##     ## 
##     ## ##     ##  ##  ##       ##          ##       ##       ####  ## ##       ##     ## ##     ## 
########  ########   ##  ##       ######       ######  ######   ## ## ##  ######  ##     ## ########  
##        ##   ##    ##  ##       ##                ## ##       ##  ####       ## ##     ## ##   ##   
##        ##    ##   ##  ##    ## ##          ##    ## ##       ##   ### ##    ## ##     ## ##    ##  
##        ##     ## ####  ######  ########     ######  ######## ##    ##  ######   #######  ##     ## 

## Realtime Cost
  - platform: template
    sensors:
      kwh_price_with_fees:
        unique_id: kwh_price_with_fees
        unit_of_measurement: "NOK"
        icon_template: mdi:currency-usd
        value_template: >
          {{ states('input_number.kwh_price_with_fees') }}


## Compensation
  - platform: template
    sensors:
      energy_compensation_daily:
        unique_id: energy_compensation_daily
        unit_of_measurement: "NOK"
        icon_template: mdi:currency-usd
        value_template: >
          {{ states('input_number.energy_compensation_daily') }}

  - platform: template
    sensors:
      kwh_price_with_compensation:
        unique_id: kwh_price_with_compensation
        unit_of_measurement: "NOK"
        icon_template: mdi:currency-usd
        value_template: >
          {{ states('input_number.kwh_price_with_compensation') }}
          
## Accumulated Cost
  - platform: template
    sensors:
      total_cost:
        unique_id: total_cost
        icon_template: mdi:currency-usd
        unit_of_measurement: "NOK"
        value_template: >
          {{ states('input_number.total_cost') }}

  - platform: template
    sensors:
      kwh_price:
        unique_id: kwh_price
        unit_of_measurement: "NOK"
        icon_template: mdi:currency-usd
        value_template: >
          {{ states('input_number.kwh_price') }}
# average
  - platform: average
    unique_id: average_kwh_usage_lasthour
    name: 'Average kwh usage last hour'
    start: '{{ now().replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    entities:
      - sensor.kwh_active_usage

  - platform: template
    sensors:
      cost_lastday:
        unique_id: cost_lastday
        icon_template: mdi:currency-usd
        unit_of_measurement: "NOK"
        value_template: >
          {{ states('input_number.cost_lastday') }}

  - platform: template
    sensors:
      cost_last_month:
        unique_id: cost_last_month
        icon_template: mdi:currency-usd
        unit_of_measurement: "NOK"
        value_template: >
          {{ states('input_number.cost_last_month') }}

  - platform: template
    sensors:
      cost_lastyear:
        unique_id: cost_lastyear
        icon_template: mdi:currency-usd
        unit_of_measurement: "NOK"
        value_template: >
          {{ states('input_number.cost_lastyear') }}


  - platform: template
    sensors:
      daily_prize_accumulated_with_fees:
        unique_id: daily_prize_accumulated_with_fees
        unit_of_measurement: NOK
        value_template: >
          {{ float(states('input_number.daily_prize_accumulated_with_fees'))| float(0) }}

  - platform: template
    sensors:
      monthly_prize_accumulated_with_fees:
        unique_id: monthly_prize_accumulated_with_fees
        unit_of_measurement: NOK
        value_template: >
          {{ float(states('input_number.monthly_prize_accumulated_with_fees'))| float(0) }}

  - platform: template
    sensors:
      monthly_prize_accumulated_with_compensation:
        unique_id: monthly_prize_accumulated_with_compensation
        unit_of_measurement: NOK
        value_template: >
          {{ float(states('input_number.monthly_prize_accumulated_with_fees')) - float(states('sensor.energy_compensation_this_month')) }}

  - platform: template
    sensors:
      yearly_prize_accumulated_with_fees:
        unique_id: yearly_prize_accumulated_with_fees
        unit_of_measurement: NOK
        value_template: >
          {{ float(states('input_number.yearly_prize_accumulated_with_fees'))| float(0) }}

  - platform: template
    sensors:
      daily_prize_accumulated_with_compensation:
        unique_id: daily_prize_accumulated_with_compensation
        unit_of_measurement: NOK
        value_template: >
          {{ float(states('input_number.daily_prize_accumulated_with_compensation'))| float(0) }}

  - platform: template
    sensors:
      monthly_avg_kwh_price:
        unique_id: monthly_avg_kwh_price
        unit_of_measurement: NOK/kWh
        value_template: >
          {{ float(states('input_number.monthly_avg_kwh_price'))| float(0) }}

  - platform: template
    sensors:
      energiledd:
        unique_id: energiledd
        unit_of_measurement: NOK/kWh
        value_template: >
          {{ float(states('input_number.energiledd'))| float(0) }}

  - platform: template  
    sensors:
      cheapest_hours_1_3:
        unique_id: "cheapest_hours_1_3"
        value_template: >-
          {% set l=state_attr('sensor.nordpool_kwh_krsand_nok_3_095_0', 'raw_today')|sort(attribute='value') %}
          {% set timeNow = now() %}
          {{  (timeNow >= l[0].start and timeNow <= l[0].end)
            or (timeNow >= l[1].start and timeNow <= l[1].end)
            or (timeNow >= l[2].start and timeNow <= l[2].end)
            or (timeNow >= l[3].start and timeNow <= l[3].end)
            or (timeNow >= l[4].start and timeNow <= l[4].end)}}

  - platform: template
    sensors:
      cheaper_after_midnight:
        unique_id: cheaper_after_midnight
        value_template: >-
          {% set l1=state_attr('sensor.nordpool_kwh_krsand_nok_3_095_0', 'raw_today')|selectattr('start', '>=', now().replace(hour=18,minute=0,second=0,microsecond=0))|sort(attribute='value') %}
          {% set l2=state_attr('sensor.nordpool_kwh_krsand_nok_3_095_0', 'raw_tomorrow')|selectattr('start', '<', (now()+timedelta(days=1)).replace(hour=6,minute=0,second=0,microsecond=0))|sort(attribute='value') %}
          {% set l3=state_attr('sensor.nordpool_kwh_krsand_nok_3_095_0', 'raw_tomorrow')|selectattr('start', '>=', (now()+timedelta(days=1)).replace(hour=6,minute=0,second=0,microsecond=0))|sort(attribute='value') %}
          {% if now().hour>=14 and l3|length>0 and l2|length>0 and l1|length>0 %}
          {{ float(l2[0].value)<float(l1[0].value) and float(l2[0].value)<float(l3[0].value)}}
          {% else %}
          False
          {% endif %}


input_number:

##    ## ##      ## ##     ##    #### ##    ## ########  ##     ## ########    ##    ## ##     ## ##     ## ########  ######## ########  
##   ##  ##  ##  ## ##     ##     ##  ###   ## ##     ## ##     ##    ##       ###   ## ##     ## ###   ### ##     ## ##       ##     ## 
##  ##   ##  ##  ## ##     ##     ##  ####  ## ##     ## ##     ##    ##       ####  ## ##     ## #### #### ##     ## ##       ##     ## 
#####    ##  ##  ## #########     ##  ## ## ## ########  ##     ##    ##       ## ## ## ##     ## ## ### ## ########  ######   ########  
##  ##   ##  ##  ## ##     ##     ##  ##  #### ##        ##     ##    ##       ##  #### ##     ## ##     ## ##     ## ##       ##   ##   
##   ##  ##  ##  ## ##     ##     ##  ##   ### ##        ##     ##    ##       ##   ### ##     ## ##     ## ##     ## ##       ##    ##  
##    ##  ###  ###  ##     ##    #### ##    ## ##         #######     ##       ##    ##  #######  ##     ## ########  ######## ##     ##

  kwh_active_usage:
    name: Nåværende forbruk
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_total:
    name: Total forbruk
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_thismonth:
    name: Forbruk denne måneden
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_lastmonth:
    name: Forbruk sist måned
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_today:
    name: Daglig forbruk
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_lastday:
    name: Forbruk i går
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_thisyear:
    name: Forbruk hittil i år
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_max:
    name: Maks forbruk
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_min:
    name: Min forbruk
    max: 999999999
    min: 0
    step: 0.001
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  monthly_kwh_peak_hour:
    name: Strøm peak denne måneden
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  monthly_power_peak_prize:
    name: pris kapasitetledd denne måneden
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  price_usage_now:
    name: pris basert på nåværende forbruk
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_startofday:
    name: Forbruk ved start av dagen
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_startofmonth:
    name: Forbruk ved start av måneden
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter

  kwh_consumption_startofyear:
    name: Forbruk ved start av året
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:counter
########  ########  ####  ######  ########    #### ##    ## ########  ##     ## ########    ##    ## ##     ## ##     ## ########  ######## ########  
##     ## ##     ##  ##  ##    ## ##           ##  ###   ## ##     ## ##     ##    ##       ###   ## ##     ## ###   ### ##     ## ##       ##     ## 
##     ## ##     ##  ##  ##       ##           ##  ####  ## ##     ## ##     ##    ##       ####  ## ##     ## #### #### ##     ## ##       ##     ## 
########  ########   ##  ##       ######       ##  ## ## ## ########  ##     ##    ##       ## ## ## ##     ## ## ### ## ########  ######   ########  
##        ##   ##    ##  ##       ##           ##  ##  #### ##        ##     ##    ##       ##  #### ##     ## ##     ## ##     ## ##       ##   ##   
##        ##    ##   ##  ##    ## ##           ##  ##   ### ##        ##     ##    ##       ##   ### ##     ## ##     ## ##     ## ##       ##    ##  
##        ##     ## ####  ######  ########    #### ##    ## ##         #######     ##       ##    ##  #######  ##     ## ########  ######## ##     ## 

  cost_lastday:
    name: Konstnad forrige dag
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  cost_last_month:
    name: Konstnad forrige måned
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  cost_lastyear:
    name: Konstnad forrige året.
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  total_cost:
    name: Total kostnad fra oppstart
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  daily_prize_accumulated_with_fees:
    name: Daglig kostnad inkludert vat og energiledd
    max: 999999999
    min: -10000
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  monthly_avg_kwh_price:
    name: månedtlig akkumulert gjensomsnitt pris for kwh
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK/kWh"
    icon: mdi:counter

  monthly_prize_accumulated_with_fees:
    name: Måndeltig kostnad inkludert vat
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  yearly_prize_accumulated_with_fees:
    name: Årlig kostnad inkludert vat
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  daily_prize_accumulated_with_compensation:
    name: Daglig kostnad inkludert komensasjon
    max: 999999999
    min: -99999999
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter
    
  kwh_price:
    name: kwh kostand
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  #electricity_price_eigeland_50_with_fees:
  kwh_price_with_fees:
    name: kwh kostand inkludert avgifter
    max: 999999999
    min: -10
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter
  
  #electricity_price_eigeland_50_with_compensation:
  kwh_price_with_compensation:
    name: kwh pris inkludert kompensasjon
    max: 999999999
    min: -10
    step: 0.1
    mode: box
    unit_of_measurement: "NOK"
    icon: mdi:counter

  energy_compensation_daily:
    name: Compensation today
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK/kWh"
    icon: mdi:counter

  energiledd:
    name: energiledd day/night
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: "NOK/kWh"
    icon: mdi:counter


###########################################
########## A U T O M A T I O N S ##########
###########################################

